### ISSUE TITLE
fps lag (again)

### ISSUE THREAD

**Issue by 1ghosty** [WaffleManTheGreat/DirtyFork#6]
seems like newest update makes fps around 40 instead of last version that fixed the lag my fps was around 80-100+

**Comment by WaffleManTheGreat** [comment]
hmm
Try now! I have updated the script so now you should receive no lag whatsoever.
the new update checks every 15 seconds if a character in the game needs to be loaded into the bypass
(and loading them into aimbot/esp)
if this wait time is too much for you please let me know.
